name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r services/ai-face-service/requirements.txt
          pip install flake8
      - name: Lint with flake8
        run: |
          flake8 services/ai-face-service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 services/ai-face-service --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test-python:
    runs-on: ubuntu-latest
    needs: lint-python
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r services/ai-face-service/requirements.txt
      - name: Test with pytest
        run: |
          cd services/ai-face-service
          pytest tests

  build-and-push-python:
    runs-on: ubuntu-latest
    needs: test-python
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./services/ai-face-service
          file: ./services/ai-face-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ai-face-service:latest

  lint-dotnet:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["auth-service", "checkin-service", "customer-service"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.100"
      - name: Restore dependencies
        run: |
          if [ "${{ matrix.service }}" == "customer-service" ]; then
            dotnet restore services/customer-service/CustomerService.sln
          else
            dotnet restore services/${{ matrix.service }}
          fi
      - name: Lint
        run: |
          if [ "${{ matrix.service }}" == "customer-service" ]; then
            dotnet format services/customer-service --verify-no-changes --verbosity detailed
          else
            dotnet format --verify-no-changes --verbosity detailed services/${{ matrix.service }}
          fi

  test-dotnet:
    runs-on: ubuntu-latest
    needs: lint-dotnet
    strategy:
      matrix:
        service: ["auth-service", "checkin-service", "customer-service"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.100"
      - name: Restore dependencies
        run: |
          if [ "${{ matrix.service }}" == "customer-service" ]; then
            dotnet restore services/customer-service/CustomerService.sln
          else
            dotnet restore services/${{ matrix.service }}
          fi
      - name: Test
        run: |
          if [ "${{ matrix.service }}" == "customer-service" ]; then
            dotnet test services/customer-service/CustomerService.sln --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=teamcity /p:CoverletOutputFormat=cobertura
          else
            dotnet test services/${{ matrix.service }}/${{ matrix.service }}.csproj --no-restore
          fi

  build-and-push-dotnet:
    runs-on: ubuntu-latest
    needs: test-dotnet
    strategy:
      matrix:
        service: ["auth-service", "checkin-service", "customer-service"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./services/${{ matrix.service }}
          file: ./services/${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest
