name: CI
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.100'
    - name: Restore dependencies
      run: dotnet restore services
    - name: Lint
      run: dotnet format services --verify-no-changes --verbosity detailed
